# Generated by Django 3.1.3 on 2020-11-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nathaniel', '0003_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='chauffeur',
            name='car',
            field=models.CharField(default='Regular car', max_length=255),
        ),
    ]
