# Generated by Django 3.1.3 on 2020-12-03 21:15

import datetime
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Nathaniel', '0003_auto_20201201_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chauffeur',
            name='date_inscription',
            field=models.DateField(default=datetime.date(2020, 12, 3)),
        ),
        migrations.AlterField(
            model_name='chauffeur',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(2020, 12, 3)),
        ),
        migrations.AlterField(
            model_name='chauffeur',
            name='num_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+972', max_length=128, null=True, region=None, unique=True),
        ),
    ]
