# Generated by Django 3.1.3 on 2020-12-09 13:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Nathaniel', '0004_auto_20201203_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='chauffeur',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='num_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+972', max_length=128, null=True, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='chauffeur',
            name='date_inscription',
            field=models.DateField(default=datetime.date(2020, 12, 9)),
        ),
        migrations.AlterField(
            model_name='chauffeur',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(2020, 12, 9)),
        ),
    ]
