# Generated by Django 3.1.3 on 2020-11-15 17:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nathaniel', '0004_chauffeur_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chauffeur',
            name='date_inscription',
            field=models.DateField(default=datetime.date(2020, 11, 15)),
        ),
        migrations.AlterField(
            model_name='chauffeur',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(2020, 11, 15)),
        ),
    ]
