# Generated by Django 3.1.3 on 2021-03-28 23:15

import datetime
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Nathaniel', '0005_auto_20201209_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chauffeur',
            name='date_inscription',
            field=models.DateField(default=datetime.date(2021, 3, 29)),
        ),
        migrations.AlterField(
            model_name='chauffeur',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(2021, 3, 29)),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(default='where do you want to go ? '),
        ),
        migrations.AlterField(
            model_name='post',
            name='num_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+972', max_length=128, null=True, region=None),
        ),
    ]
