# Generated by Django 3.1.3 on 2021-04-10 22:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nathaniel', '0006_auto_20210329_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='chauffeur',
            name='hour',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='chauffeur',
            name='date_inscription',
            field=models.DateField(default=datetime.date(2021, 4, 11)),
        ),
        migrations.AlterField(
            model_name='chauffeur',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(2021, 4, 11)),
        ),
        migrations.AlterField(
            model_name='post',
            name='titre',
            field=models.CharField(default='', max_length=150, null=True),
        ),
    ]
