# Generated by Django 3.1.3 on 2021-04-14 13:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nathaniel', '0007_auto_20210411_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chauffeur',
            name='date_inscription',
            field=models.DateField(default=datetime.date(2021, 4, 14)),
        ),
        migrations.AlterField(
            model_name='chauffeur',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(2021, 4, 14)),
        ),
        migrations.AlterField(
            model_name='post',
            name='other',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
