# Generated by Django 3.1.3 on 2021-05-13 11:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nathaniel', '0007_auto_20210513_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chauffeur',
            name='course',
        ),
        migrations.AlterField(
            model_name='chauffeur',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 13, 14, 50, 18, 812)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 13, 14, 50, 18, 812)),
        ),
    ]
