# Generated by Django 3.1.3 on 2021-04-14 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nathaniel', '0008_auto_20210414_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='other',
            field=models.DateTimeField(),
        ),
    ]
