# Generated by Django 3.1.3 on 2021-05-14 09:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nathaniel', '0010_auto_20210415_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chauffeur',
            name='date_inscription',
            field=models.DateField(default=datetime.date(2021, 5, 14)),
        ),
        migrations.AlterField(
            model_name='chauffeur',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(2021, 5, 14)),
        ),
        migrations.AlterField(
            model_name='post',
            name='other',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 14, 12, 26, 57, 251181)),
        ),
    ]
