# Generated by Django 3.1.3 on 2021-06-06 10:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Nathaniel', '0011_auto_20210514_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chauffeur',
            name='course',
        ),
        migrations.AlterField(
            model_name='chauffeur',
            name='date_inscription',
            field=models.DateField(default=datetime.datetime(2021, 6, 6, 10, 21, 30, 79461, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='chauffeur',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2021, 6, 6, 10, 21, 30, 79461, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='other',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 6, 13, 21, 30, 532730)),
        ),
    ]
