# Generated by Django 3.1.3 on 2021-08-09 08:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Nathaniel', '0011_auto_20210514_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('car_image', models.ImageField(default='hotelsample.jpg', null=True, upload_to='images/')),
                ('num_phone', phonenumber_field.modelfields.PhoneNumberField(default='+972', max_length=128, null=True, region=None, unique=True)),
                ('depart', models.CharField(default='tahanat mercazit netanya', max_length=255)),
                ('arrivé', models.CharField(default='bengourion', max_length=255)),
                ('time', models.TimeField(auto_now=True)),
                ('confirmation', models.BooleanField(default=False, verbose_name='confirmer votre trajet ')),
            ],
        ),
        migrations.RemoveField(
            model_name='chauffeur',
            name='course',
        ),
        migrations.RemoveField(
            model_name='chauffeur',
            name='hour',
        ),
        migrations.RemoveField(
            model_name='post',
            name='other',
        ),
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 9, 11, 47, 44, 718038)),
        ),
        migrations.AlterField(
            model_name='chauffeur',
            name='date_inscription',
            field=models.DateField(default=datetime.datetime(2021, 8, 9, 8, 47, 44, 514851, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='chauffeur',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2021, 8, 9, 8, 47, 44, 514851, tzinfo=utc)),
        ),
    ]
