# Generated by Django 3.1.3 on 2021-06-08 08:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Nathaniel', '0012_auto_20210606_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chauffeur',
            name='date_inscription',
            field=models.DateField(default=datetime.datetime(2021, 6, 8, 8, 9, 19, 370877, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='chauffeur',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2021, 6, 8, 8, 9, 19, 370877, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='other',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 8, 11, 9, 19, 826990)),
        ),
    ]
