# Generated by Django 3.1.3 on 2021-06-11 13:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Nathaniel', '0013_auto_20210608_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chauffeur',
            name='date_inscription',
            field=models.DateField(default=datetime.datetime(2021, 6, 11, 13, 35, 1, 617321, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='chauffeur',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2021, 6, 11, 13, 35, 1, 617321, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='other',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 11, 16, 35, 1, 948332)),
        ),
    ]
