# Generated by Django 3.1.3 on 2021-06-21 05:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Nathaniel', '0014_auto_20210611_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chauffeur',
            name='date_inscription',
            field=models.DateField(default=datetime.datetime(2021, 6, 21, 5, 34, 43, 299797, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='chauffeur',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2021, 6, 21, 5, 34, 43, 299797, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='other',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 21, 8, 34, 43, 471667)),
        ),
    ]
