# Generated by Django 3.1.3 on 2021-06-21 05:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Nathaniel', '0015_auto_20210621_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='chauffeur',
            name='course',
            field=models.ForeignKey(default='netanya-bengourion', on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chauffeur',
            name='date_inscription',
            field=models.DateField(default=datetime.datetime(2021, 6, 21, 5, 38, 36, 638437, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='chauffeur',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2021, 6, 21, 5, 38, 36, 638437, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='other',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 21, 8, 38, 36, 825931)),
        ),
    ]
