# Generated by Django 3.1.3 on 2021-06-29 09:45

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Nathaniel', '0016_auto_20210621_0840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='other',
        ),
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 29, 12, 45, 4, 184546)),
        ),
        migrations.AlterField(
            model_name='chauffeur',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Nathaniel.post'),
        ),
        migrations.AlterField(
            model_name='chauffeur',
            name='date_inscription',
            field=models.DateField(default=datetime.datetime(2021, 6, 29, 9, 45, 3, 817519, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='chauffeur',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2021, 6, 29, 9, 45, 3, 817519, tzinfo=utc)),
        ),
    ]
