# Generated by Django 3.1.3 on 2021-07-16 05:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Nathaniel', '0017_auto_20210629_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('car_image', models.ImageField(default='hotelsample.jpg', null=True, upload_to='images/')),
                ('num_phone', phonenumber_field.modelfields.PhoneNumberField(default='+972', max_length=128, null=True, region=None, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='chauffeur',
            name='date_inscription',
            field=models.DateField(default=datetime.datetime(2021, 7, 16, 5, 38, 34, 417748, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='chauffeur',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2021, 7, 16, 5, 38, 34, 417748, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 16, 8, 38, 34, 792862)),
        ),
    ]
