# Generated by Django 3.1.3 on 2021-07-16 06:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Nathaniel', '0018_auto_20210716_0838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chauffeur',
            name='course',
        ),
        migrations.RemoveField(
            model_name='chauffeur',
            name='hour',
        ),
        migrations.AlterField(
            model_name='chauffeur',
            name='date_inscription',
            field=models.DateField(default=datetime.datetime(2021, 7, 16, 6, 29, 3, 488793, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='chauffeur',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2021, 7, 16, 6, 29, 3, 488793, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 16, 9, 29, 4, 67093)),
        ),
    ]
