# Generated by Django 3.1.3 on 2021-08-09 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0003_auto_20210805_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='user_anonimous.jpg', null=True, upload_to='images/'),
        ),
    ]
